'use strict'

module = angular.module 'ee-font-selector', []

module.directive "eeFontSelector", () ->
  templateUrl: 'ee-shared/components/ee-font-selector.html'
  restrict: 'E'
  scope:
    family: '='
  link: (scope, ele, attrs) ->
    scope.setFamily = (font) -> scope.family = font

    scope.fonts = [
      # Normal
      'Amaranth'
      'Philosopher'
      'Varela Round'
      'Bree Serif'
      # Medium
      'Berkshire Swash'
      'Lobster Two'
      'Pacifico'
      'Chelsea Market'
      # Thin
      'Indie Flower'
      'Amatic SC'
      'Poiret One'
      'Cinzel'
      # Bold
      'Limelight'
      'Permanent Marker'
      'Luckiest Guy'
      'Bevan'
      # 'Sigmar One'
      # 'Bangers'
      # 'Architects Daughter'
      # 'Lato'
      # 'Anton'
      # 'Acme'
      # 'Noto Serif'
      # 'Chewy'
      # 'Alegreya'
      # 'Love Ya Like A Sister'
      # 'Tangerine'
      # 'Cantora One'
      # 'Cherry Swash'
      # 'Open Sans'
      # 'Roboto'
      # 'Roboto Condensed'
      # 'Inconsolata'
      # 'Josefin Sans'
      # 'Ubuntu'
      # 'Oswald'
      # 'Audiowide'
      # 'Gorditas'
      # 'Raleway'
      # 'Arvo'
      # 'Slabo 27px'
      # 'Montserrat'
      # 'Dosis'
      # 'Lily Script One'
      # 'Knewave'
      # 'Lobster'
      # 'Dancing Script'
      # 'Shadows Into Light'
      # 'Mountains of Christmas'
      # 'Julius Sans One'
      # 'Satisfy'
      # 'Russo One'
      # 'PT Sans Caption'
      # 'Maven Pro'
      # 'Quicksand'
      # 'ABeeZee'
      # 'Abel'
      # 'Abril Fatface'
      # 'Aclonica'
      # 'Actor'
      # 'Adamina'
      # 'Advent Pro'
      # 'Aguafina Script'
      # 'Akronim'
      # 'Aladin'
      # 'Aldrich'
      # 'Alef'
      # 'Alegreya SC'
      # 'Alegreya Sans'
      # 'Alegreya Sans SC'
      # 'Alex Brush'
      # 'Alfa Slab One'
      # 'Alice'
      # 'Alike'
      # 'Alike Angular'
      # 'Allan'
      # 'Allerta'
      # 'Allerta Stencil'
      # 'Allura'
      # 'Almendra'
      # 'Almendra Display'
      # 'Almendra SC'
      # 'Amarante'
      # 'Amethysta'
      # 'Amiri'
      # 'Amita'
      # 'Anaheim'
      # 'Andada'
      # 'Andika'
      # 'Angkor'
      # 'Annie Use Your Telescope'
      # 'Anonymous Pro'
      # 'Antic'
      # 'Antic Didone'
      # 'Antic Slab'
      # 'Arapey'
      # 'Arbutus'
      # 'Arbutus Slab'
      # 'Archivo Black'
      # 'Archivo Narrow'
      # 'Arimo'
      # 'Arizonia'
      # 'Armata'
      # 'Artifika'
      # 'Arya'
      # 'Asap'
      # 'Asar'
      # 'Asset'
      # 'Astloch'
      # 'Asul'
      # 'Atomic Age'
      # 'Aubrey'
      # 'Autour One'
      # 'Average'
      # 'Average Sans'
      # 'Averia Gruesa Libre'
      # 'Averia Libre'
      # 'Averia Sans Libre'
      # 'Averia Serif Libre'
      # 'Bad Script'
      # 'Balthazar'
      # 'Basic'
      # 'Battambang'
      # 'Baumans'
      # 'Bayon'
      # 'Belgrano'
      # 'Belleza'
      # 'BenchNine'
      # 'Bentham'
      # 'Bigelow Rules'
      # 'Bigshot One'
      # 'Bilbo'
      # 'Bilbo Swash Caps'
      # 'Biryani'
      # 'Bitter'
      # 'Black Ops One'
      # 'Bokor'
      # 'Bonbon'
      # 'Boogaloo'
      # 'Bowlby One'
      # 'Bowlby One SC'
      # 'Brawler'
      # 'Bubblegum Sans'
      # 'Bubbler One'
      # 'Buda'
      # 'Buenard'
      # 'Butcherman'
      # 'Butterfly Kids'
      # 'Cabin'
      # 'Cabin Condensed'
      # 'Cabin Sketch'
      # 'Caesar Dressing'
      # 'Cagliostro'
      # 'Calligraffitti'
      # 'Cambay'
      # 'Cambo'
      # 'Candal'
      # 'Cantarell'
      # 'Cantata One'
      # 'Capriola'
      # 'Cardo'
      # 'Carme'
      # 'Carrois Gothic'
      # 'Carrois Gothic SC'
      # 'Carter One'
      # 'Catamaran'
      # 'Caudex'
      # 'Caveat'
      # 'Caveat Brush'
      # 'Cedarville Cursive'
      # 'Ceviche One'
      # 'Changa One'
      # 'Chango'
      # 'Chau Philomene One'
      # 'Chela One'
      # 'Chenla'
      # 'Cherry Cream Soda'
      # 'Chicle'
      # 'Chivo'
      # 'Chonburi'
      # 'Cinzel Decorative'
      # 'Clicker Script'
      # 'Coda'
      # 'Coda Caption'
      # 'Codystar'
      # 'Combo'
      # 'Comfortaa'
      # 'Coming Soon'
      # 'Concert One'
      # 'Condiment'
      # 'Content'
      # 'Contrail One'
      # 'Convergence'
      # 'Cookie'
      # 'Copse'
      # 'Corben'
      # 'Courgette'
      # 'Cousine'
      # 'Coustard'
      # 'Covered By Your Grace'
      # 'Crafty Girls'
      # 'Creepster'
      # 'Crete Round'
      # 'Crimson Text'
      # 'Croissant One'
      # 'Crushed'
      # 'Cuprum'
      # 'Cutive'
      # 'Cutive Mono'
      # 'Damion'
      # 'Dangrek'
      # 'Dawning of a New Day'
      # 'Days One'
      # 'Dekko'
      # 'Delius'
      # 'Delius Swash Caps'
      # 'Delius Unicase'
      # 'Della Respira'
      # 'Denk One'
      # 'Devonshire'
      # 'Dhurjati'
      # 'Didact Gothic'
      # 'Diplomata'
      # 'Diplomata SC'
      # 'Domine'
      # 'Donegal One'
      # 'Doppio One'
      # 'Dorsa'
      # 'Dr Sugiyama'
      # 'Droid Sans'
      # 'Droid Sans Mono'
      # 'Droid Serif'
      # 'Duru Sans'
      # 'Dynalight'
      # 'EB Garamond'
      # 'Eagle Lake'
      # 'Eater'
      # 'Economica'
      # 'Eczar'
      # 'Ek Mukta'
      # 'Electrolize'
      # 'Elsie'
      # 'Elsie Swash Caps'
      # 'Emblema One'
      # 'Emilys Candy'
      # 'Engagement'
      # 'Englebert'
      # 'Enriqueta'
      # 'Erica One'
      # 'Esteban'
      # 'Euphoria Script'
      # 'Ewert'
      # 'Exo'
      # 'Exo 2'
      # 'Expletus Sans'
      # 'Fanwood Text'
      # 'Fascinate'
      # 'Fascinate Inline'
      # 'Faster One'
      # 'Fasthand'
      # 'Fauna One'
      # 'Federant'
      # 'Federo'
      # 'Felipa'
      # 'Fenix'
      # 'Finger Paint'
      # 'Fira Mono'
      # 'Fira Sans'
      # 'Fjalla One'
      # 'Fjord One'
      # 'Flamenco'
      # 'Flavors'
      # 'Fondamento'
      # 'Fontdiner Swanky'
      # 'Forum'
      # 'Francois One'
      # 'Freckle Face'
      # 'Fredericka the Great'
      # 'Fredoka One'
      # 'Freehand'
      # 'Fresca'
      # 'Frijole'
      # 'Fruktur'
      # 'Fugaz One'
      # 'GFS Didot'
      # 'GFS Neohellenic'
      # 'Gabriela'
      # 'Gafata'
      # 'Galdeano'
      # 'Galindo'
      # 'Gentium Basic'
      # 'Gentium Book Basic'
      # 'Geo'
      # 'Geostar'
      # 'Geostar Fill'
      # 'Germania One'
      # 'Gidugu'
      # 'Gilda Display'
      # 'Give You Glory'
      # 'Glass Antiqua'
      # 'Glegoo'
      # 'Gloria Hallelujah'
      # 'Goblin One'
      # 'Gochi Hand'
      # 'Goudy Bookletter 1911'
      # 'Graduate'
      # 'Grand Hotel'
      # 'Gravitas One'
      # 'Great Vibes'
      # 'Griffy'
      # 'Gruppo'
      # 'Gudea'
      # 'Gurajada'
      # 'Habibi'
      # 'Halant'
      # 'Hammersmith One'
      # 'Hanalei'
      # 'Hanalei Fill'
      # 'Handlee'
      # 'Hanuman'
      # 'Happy Monkey'
      # 'Headland One'
      # 'Henny Penny'
      # 'Herr Von Muellerhoff'
      # 'Hind'
      # 'Hind Siliguri'
      # 'Hind Vadodara'
      # 'Holtwood One SC'
      # 'Homemade Apple'
      # 'Homenaje'
      # 'IM Fell DW Pica'
      # 'IM Fell DW Pica SC'
      # 'IM Fell Double Pica'
      # 'IM Fell Double Pica SC'
      # 'IM Fell English'
      # 'IM Fell English SC'
      # 'IM Fell French Canon'
      # 'IM Fell French Canon SC'
      # 'IM Fell Great Primer'
      # 'IM Fell Great Primer SC'
      # 'Iceberg'
      # 'Iceland'
      # 'Imprima'
      # 'Inder'
      # 'Inika'
      # 'Inknut Antiqua'
      # 'Irish Grover'
      # 'Istok Web'
      # 'Italiana'
      # 'Italianno'
      # 'Itim'
      # 'Jacques Francois'
      # 'Jacques Francois Shadow'
      # 'Jaldi'
      # 'Jim Nightshade'
      # 'Jockey One'
      # 'Jolly Lodger'
      # 'Josefin Slab'
      # 'Joti One'
      # 'Judson'
      # 'Julee'
      # 'Junge'
      # 'Jura'
      # 'Just Another Hand'
      # 'Just Me Again Down Here'
      # 'Kadwa'
      # 'Kalam'
      # 'Kameron'
      # 'Kantumruy'
      # 'Karla'
      # 'Karma'
      # 'Kaushan Script'
      # 'Kavoon'
      # 'Kdam Thmor'
      # 'Keania One'
      # 'Kelly Slab'
      # 'Kenia'
      # 'Khand'
      # 'Khmer'
      # 'Khula'
      # 'Kite One'
      # 'Kotta One'
      # 'Koulen'
      # 'Kranky'
      # 'Kreon'
      # 'Kristi'
      # 'Krona One'
      # 'Kurale'
      # 'La Belle Aurore'
      # 'Laila'
      # 'Lakki Reddy'
      # 'Lancelot'
      # 'Lateef'
      # 'League Script'
      # 'Leckerli One'
      # 'Ledger'
      # 'Lekton'
      # 'Lemon'
      # 'Libre Baskerville'
      # 'Life Savers'
      # 'Lilita One'
      # 'Linden Hill'
      # 'Londrina Outline'
      # 'Londrina Shadow'
      # 'Londrina Sketch'
      # 'Londrina Solid'
      # 'Lora'
      # 'Loved by the King'
      # 'Lovers Quarrel'
      # 'Lusitana'
      # 'Lustria'
      # 'Macondo'
      # 'Macondo Swash Caps'
      # 'Magra'
      # 'Maiden Orange'
      # 'Mako'
      # 'Mallanna'
      # 'Mandali'
      # 'Marcellus'
      # 'Marcellus SC'
      # 'Marck Script'
      # 'Margarine'
      # 'Marko One'
      # 'Marmelad'
      # 'Martel'
      # 'Martel Sans'
      # 'Marvel'
      # 'Mate'
      # 'Mate SC'
      # 'McLaren'
      # 'Meddon'
      # 'MedievalSharp'
      # 'Medula One'
      # 'Megrim'
      # 'Meie Script'
      # 'Merienda'
      # 'Merienda One'
      # 'Merriweather'
      # 'Merriweather Sans'
      # 'Metal'
      # 'Metal Mania'
      # 'Metamorphous'
      # 'Metrophobic'
      # 'Michroma'
      # 'Milonga'
      # 'Miltonian'
      # 'Miltonian Tattoo'
      # 'Miniver'
      # 'Miss Fajardose'
      # 'Modak'
      # 'Modern Antiqua'
      # 'Molengo'
      # 'Molle'
      # 'Monda'
      # 'Monofett'
      # 'Monoton'
      # 'Monsieur La Doulaise'
      # 'Montaga'
      # 'Montez'
      # 'Montserrat Alternates'
      # 'Montserrat Subrayada'
      # 'Moul'
      # 'Moulpali'
      # 'Mouse Memoirs'
      # 'Mr Bedfort'
      # 'Mr Dafoe'
      # 'Mr De Haviland'
      # 'Mrs Saint Delafield'
      # 'Mrs Sheppards'
      # 'Muli'
      # 'Mystery Quest'
      # 'NTR'
      # 'Neucha'
      # 'Neuton'
      # 'New Rocker'
      # 'News Cycle'
      # 'Niconne'
      # 'Nixie One'
      # 'Nobile'
      # 'Nokora'
      # 'Norican'
      # 'Nosifer'
      # 'Nothing You Could Do'
      # 'Noticia Text'
      # 'Noto Sans'
      # 'Nova Cut'
      # 'Nova Flat'
      # 'Nova Mono'
      # 'Nova Oval'
      # 'Nova Round'
      # 'Nova Script'
      # 'Nova Slim'
      # 'Nova Square'
      # 'Numans'
      # 'Nunito'
      # 'Odor Mean Chey'
      # 'Offside'
      # 'Old Standard TT'
      # 'Oldenburg'
      # 'Oleo Script'
      # 'Oleo Script Swash Caps'
      # 'Open Sans Condensed'
      # 'Oranienbaum'
      # 'Orbitron'
      # 'Oregano'
      # 'Orienta'
      # 'Original Surfer'
      # 'Over the Rainbow'
      # 'Overlock'
      # 'Overlock SC'
      # 'Ovo'
      # 'Oxygen'
      # 'Oxygen Mono'
      # 'PT Mono'
      # 'PT Sans'
      # 'PT Sans Narrow'
      # 'PT Serif'
      # 'PT Serif Caption'
      # 'Palanquin'
      # 'Palanquin Dark'
      # 'Paprika'
      # 'Parisienne'
      # 'Passero One'
      # 'Passion One'
      # 'Pathway Gothic One'
      # 'Patrick Hand'
      # 'Patrick Hand SC'
      # 'Patua One'
      # 'Paytone One'
      # 'Peddana'
      # 'Peralta'
      # 'Petit Formal Script'
      # 'Petrona'
      # 'Piedra'
      # 'Pinyon Script'
      # 'Pirata One'
      # 'Plaster'
      # 'Play'
      # 'Playball'
      # 'Playfair Display'
      # 'Playfair Display SC'
      # 'Podkova'
      # 'Poller One'
      # 'Poly'
      # 'Pompiere'
      # 'Pontano Sans'
      # 'Poppins'
      # 'Port Lligat Sans'
      # 'Port Lligat Slab'
      # 'Pragati Narrow'
      # 'Prata'
      # 'Preahvihear'
      # 'Press Start 2P'
      # 'Princess Sofia'
      # 'Prociono'
      # 'Prosto One'
      # 'Puritan'
      # 'Purple Purse'
      # 'Quando'
      # 'Quantico'
      # 'Quattrocento'
      # 'Quattrocento Sans'
      # 'Questrial'
      # 'Quintessential'
      # 'Qwigley'
      # 'Racing Sans One'
      # 'Radley'
      # 'Rajdhani'
      # 'Raleway Dots'
      # 'Ramabhadra'
      # 'Ramaraja'
      # 'Rambla'
      # 'Rammetto One'
      # 'Ranchers'
      # 'Rancho'
      # 'Ranga'
      # 'Rationale'
      # 'Ravi Prakash'
      # 'Redressed'
      # 'Reenie Beanie'
      # 'Revalia'
      # 'Rhodium Libre'
      # 'Ribeye'
      # 'Ribeye Marrow'
      # 'Righteous'
      # 'Risque'
      # 'Roboto Mono'
      # 'Roboto Slab'
      # 'Rochester'
      # 'Rock Salt'
      # 'Rokkitt'
      # 'Romanesco'
      # 'Ropa Sans'
      # 'Rosario'
      # 'Rosarivo'
      # 'Rouge Script'
      # 'Rozha One'
      # 'Rubik'
      # 'Rubik Mono One'
      # 'Rubik One'
      # 'Ruda'
      # 'Rufina'
      # 'Ruge Boogie'
      # 'Ruluko'
      # 'Rum Raisin'
      # 'Ruslan Display'
      # 'Ruthie'
      # 'Rye'
      # 'Sacramento'
      # 'Sahitya'
      # 'Sail'
      # 'Salsa'
      # 'Sanchez'
      # 'Sancreek'
      # 'Sansita One'
      # 'Sarala'
      # 'Sarina'
      # 'Sarpanch'
      # 'Scada'
      # 'Scheherazade'
      # 'Schoolbell'
      # 'Seaweed Script'
      # 'Sevillana'
      # 'Seymour One'
      # 'Shadows Into Light Two'
      # 'Shanti'
      # 'Share'
      # 'Share Tech'
      # 'Share Tech Mono'
      # 'Shojumaru'
      # 'Short Stack'
      # 'Siemreap'
      # 'Signika'
      # 'Signika Negative'
      # 'Simonetta'
      # 'Sintony'
      # 'Sirin Stencil'
      # 'Six Caps'
      # 'Skranji'
      # 'Slabo 13px'
      # 'Slabo 27px'
      # 'Slackey'
      # 'Smokum'
      # 'Smythe'
      # 'Sniglet'
      # 'Snippet'
      # 'Snowburst One'
      # 'Sofadi One'
      # 'Sofia'
      # 'Sonsie One'
      # 'Sorts Mill Goudy'
      # 'Source Code Pro'
      # 'Source Sans Pro'
      # 'Source Serif Pro'
      # 'Special Elite'
      # 'Spicy Rice'
      # 'Spinnaker'
      # 'Spirax'
      # 'Squada One'
      # 'Sree Krushnadevaraya'
      # 'Stalemate'
      # 'Stalinist One'
      # 'Stardos Stencil'
      # 'Stint Ultra Condensed'
      # 'Stint Ultra Expanded'
      # 'Stoke'
      # 'Strait'
      # 'Sue Ellen Francisco'
      # 'Sumana'
      # 'Sunshiney'
      # 'Supermercado One'
      # 'Sura'
      # 'Suranna'
      # 'Suravaram'
      # 'Suwannaphum'
      # 'Swanky and Moo Moo'
      # 'Syncopate'
      # 'Taprom'
      # 'Tauri'
      # 'Teko'
      # 'Telex'
      # 'Tenali Ramakrishna'
      # 'Tenor Sans'
      # 'Text Me One'
      # 'The Girl Next Door'
      # 'Tienne'
      # 'Tillana'
      # 'Timmana'
      # 'Tinos'
      # 'Titan One'
      # 'Titillium Web'
      # 'Trade Winds'
      # 'Trocchi'
      # 'Trochut'
      # 'Trykker'
      # 'Tulpen One'
      # 'Ubuntu Condensed'
      # 'Ubuntu Mono'
      # 'Ultra'
      # 'Uncial Antiqua'
      # 'Underdog'
      # 'Unica One'
      # 'UnifrakturCook'
      # 'UnifrakturMaguntia'
      # 'Unkempt'
      # 'Unlock'
      # 'Unna'
      # 'VT323'
      # 'Vampiro One'
      # 'Varela'
      # 'Vast Shadow'
      # 'Vesper Libre'
      # 'Vibur'
      # 'Vidaloka'
      # 'Viga'
      # 'Voces'
      # 'Volkhov'
      # 'Vollkorn'
      # 'Voltaire'
      # 'Waiting for the Sunrise'
      # 'Wallpoet'
      # 'Walter Turncoat'
      # 'Warnes'
      # 'Wellfleet'
      # 'Wendy One'
      # 'Wire One'
      # 'Work Sans'
      # 'Yanone Kaffeesatz'
      # 'Yantramanav'
      # 'Yellowtail'
      # 'Yeseva One'
      # 'Yesteryear'
      # 'Zeyada'
    ]

    return
